"""
Clean ACR Module 1 CT-number analysis service.

Generated by clean_module1_backend_v22_extract_final.py.
This file is intentionally single-version: no stacked patch wrappers.
Future changes should replace this file or replace one clearly marked section,
not append wrapper after wrapper.
"""

from __future__ import annotations

# BEGIN GLOBAL CV2 IMPORT FIX
# OpenCV is required by Module 1 circle/line detection.
# This must be a real global name because cleaned helper functions call cv2.* directly.
try:
    import cv2
except ImportError:  # handled by the analysis functions at runtime
    cv2 = None
# END GLOBAL CV2 IMPORT FIX
import base64
import io
import math
import re
import zipfile
from pathlib import Path
from typing import Any
import numpy as np
from io import BytesIO
from PIL import ImageDraw
from services.acr_module_classifier import (
    CLASSIFIER_VERSION,
    _estimate_phantom_geometry,
    create_acr_module_classification,
)
from services.dicom_display import (
    _get_slices_from_stack_or_upload,
    window_pixels_to_image,
)

MODULE1_ANALYSIS_VERSION = "ACR_MODULE1_CT_NUMBER_CLEAN_V33_FAST_LARGE_WATER_CIRCLE_2026_07_26"

MODULE_1 = "MODULE_1_CT_NUMBER"

M1_V13_MATERIAL_ROI_AREA_MM2 = 100.0

M1_V13_WATER_ROI_AREA_MM2 = 400.0

def _image_to_data_url(image) -> str:
    stream = BytesIO()
    image.save(stream, format="PNG")
    encoded = base64.b64encode(stream.getvalue()).decode("ascii")
    return "data:image/png;base64," + encoded

def _require_number(value: Any, name: str) -> float:
    try:
        number = float(value)
    except Exception as exc:
        raise ValueError(f"{name} is missing or invalid.") from exc

    if not math.isfinite(number) or number <= 0:
        raise ValueError(f"{name} must be a positive finite number.")

    return number

def _normalize_to_uint8(raw: np.ndarray) -> np.ndarray:
    arr = np.asarray(raw, dtype=np.float32)
    finite = arr[np.isfinite(arr)]

    if finite.size < 20:
        raise ValueError("Not enough finite pixels for Module 1 detection.")

    low = float(np.percentile(finite, 0.5))
    high = float(np.percentile(finite, 99.5))

    if high <= low:
        low = float(np.min(finite))
        high = float(np.max(finite))

    if high <= low:
        return np.zeros(arr.shape, dtype=np.uint8)

    normalized = np.clip((arr - low) / (high - low), 0.0, 1.0)
    return (normalized * 255.0).astype(np.uint8)

def _merge_circles(circles: list[tuple[float, float, float]]) -> list[tuple[float, float, float]]:
    merged: list[tuple[float, float, float]] = []

    for x_value, y_value, radius in sorted(circles, key=lambda item: item[2], reverse=True):
        duplicate = False

        for kept_x, kept_y, kept_radius in merged:
            distance = math.hypot(x_value - kept_x, y_value - kept_y)

            if distance < max(radius, kept_radius) * 0.65:
                duplicate = True
                break

        if not duplicate:
            merged.append((float(x_value), float(y_value), float(radius)))

    return merged

def _detect_insert_circles(
    raw: np.ndarray,
    phantom_cx: float,
    phantom_cy: float,
    phantom_radius: float,
) -> tuple[list[tuple[float, float, float]], dict[str, Any]]:
    if cv2 is None:
        raise ValueError(
            "OpenCV is not installed. Run: py -m pip install opencv-python"
        )

    img_8bit = _normalize_to_uint8(raw)

    clahe = cv2.createCLAHE(
        clipLimit=3.0,
        tileGridSize=(8, 8),
    )
    enhanced = clahe.apply(img_8bit)
    blurred = cv2.GaussianBlur(
        enhanced,
        (9, 9),
        2,
    )

    height, width = raw.shape
    min_dim = min(height, width)

    min_radius = max(
        8,
        int(round(min_dim * 0.035)),
    )
    max_radius = max(
        min_radius + 4,
        int(round(min_dim * 0.16)),
    )
    min_dist = max(
        35,
        int(round(min_dim * 0.10)),
    )

    raw_circles = cv2.HoughCircles(
        blurred,
        cv2.HOUGH_GRADIENT,
        dp=1.2,
        minDist=min_dist,
        param1=30,
        param2=25,
        minRadius=min_radius,
        maxRadius=max_radius,
    )

    detected: list[tuple[float, float, float]] = []

    if raw_circles is not None:
        for x_value, y_value, radius in raw_circles[0, :]:
            x_float = float(x_value)
            y_float = float(y_value)
            r_float = float(radius)

            distance_from_center = math.hypot(
                x_float - phantom_cx,
                y_float - phantom_cy,
            )

            if distance_from_center + r_float > phantom_radius * 0.96:
                continue

            if r_float < min_radius or r_float > max_radius:
                continue

            detected.append((x_float, y_float, r_float))

    detected = _merge_circles(detected)

    detected = sorted(
        detected,
        key=lambda circle: (
            abs(math.hypot(circle[0] - phantom_cx, circle[1] - phantom_cy) - phantom_radius * 0.45),
            -circle[2],
        ),
    )[:8]

    detected = sorted(
        detected,
        key=lambda circle: math.atan2(circle[1] - phantom_cy, circle[0] - phantom_cx),
    )

    diagnostics = {
        "method": "CLAHE + Gaussian blur + OpenCV HoughCircles",
        "minRadiusPixels": int(min_radius),
        "maxRadiusPixels": int(max_radius),
        "minDistancePixels": int(min_dist),
        "detectedCircleCount": int(len(detected)),
    }

    return detected, diagnostics

def _ellipse_mask_pixels(
    shape: tuple[int, int],
    cx: float,
    cy: float,
    radius_x: float,
    radius_y: float,
) -> np.ndarray:
    height, width = shape
    yy, xx = np.ogrid[:height, :width]

    return (
        ((xx - float(cx)) / max(float(radius_x), 1e-6)) ** 2
        + ((yy - float(cy)) / max(float(radius_y), 1e-6)) ** 2
    ) <= 1.0

def _measure_roi(
    raw: np.ndarray,
    label: str,
    cx: float,
    cy: float,
    radius_x_pixels: float,
    radius_y_pixels: float,
    row_spacing: float,
    col_spacing: float,
    display_radius_pixels: float | None = None,
    full_detected_radius_pixels: float | None = None,
) -> dict[str, Any]:
    mask = _ellipse_mask_pixels(
        shape=raw.shape,
        cx=cx,
        cy=cy,
        radius_x=radius_x_pixels,
        radius_y=radius_y_pixels,
    )

    values = raw[mask]
    values = values[np.isfinite(values)]

    if values.size < 10:
        raise ValueError(f"{label} ROI contains too few valid pixels.")

    actual_area_mm2 = float(values.size * row_spacing * col_spacing)

    return {
        "label": label,
        "cx": round(float(cx), 3),
        "cy": round(float(cy), 3),
        "radiusX": round(float(radius_x_pixels), 3),
        "radiusY": round(float(radius_y_pixels), 3),
        "displayRadiusPixels": round(float(display_radius_pixels or radius_x_pixels), 3),
        "detectedRadiusPixels": (
            round(float(full_detected_radius_pixels), 3)
            if full_detected_radius_pixels is not None
            else None
        ),
        "actualAreaMm2": round(float(actual_area_mm2), 2),
        "pixelCount": int(values.size),
        "meanHU": round(float(np.mean(values)), 2),
        "stdHU": round(float(np.std(values)), 2),
        "result": "MEASURED",
    }

def _module1_v10_candidate_indices(
    classification: dict[str, Any],
    slice_count: int,
) -> list[int]:
    indices: list[int] = []

    for group in classification.get("groups") or []:
        if group.get("prediction") != MODULE_1:
            continue

        start = int(group.get("startSliceIndex", 0))
        end = int(group.get("endSliceIndex", start))

        for index in range(start, end + 1):
            if 0 <= index < slice_count:
                indices.append(index)

    for item in classification.get("slices") or []:
        if item.get("prediction") != MODULE_1:
            continue

        index = int(
            item.get(
                "sliceIndex",
                int(item.get("sliceNumber", 1)) - 1,
            )
        )

        if 0 <= index < slice_count:
            indices.append(index)

    if not indices:
        indices = list(range(0, min(slice_count, 8)))

    return sorted(set(indices))

def _module1_v10_classifier_score_for_index(
    classification: dict[str, Any],
    index: int,
) -> float:
    for item in classification.get("slices") or []:
        item_index = int(
            item.get(
                "sliceIndex",
                int(item.get("sliceNumber", 1)) - 1,
            )
        )

        if item_index == index:
            return float(
                (item.get("scores") or {}).get(MODULE_1, 0.0)
            )

    return 0.0

def _module1_v10_group_for_index(
    classification: dict[str, Any],
    index: int,
) -> dict[str, Any] | None:
    for group in classification.get("groups") or []:
        if group.get("prediction") != MODULE_1:
            continue

        if (
            int(group.get("startSliceIndex", -1))
            <= index
            <= int(group.get("endSliceIndex", -1))
        ):
            return group

    return None

def _module1_v10_slice_record_for_index(
    classification: dict[str, Any],
    index: int,
) -> dict[str, Any] | None:
    for item in classification.get("slices") or []:
        item_index = int(
            item.get(
                "sliceIndex",
                int(item.get("sliceNumber", 1)) - 1,
            )
        )

        if item_index == index:
            return item

    return None

def _module1_v10_basic_roi_stats(
    raw: np.ndarray,
    cx: float,
    cy: float,
    radius_pixels: float,
) -> dict[str, float] | None:
    try:
        mask = _ellipse_mask_pixels(
            shape=raw.shape,
            cx=cx,
            cy=cy,
            radius_x=radius_pixels,
            radius_y=radius_pixels,
        )
        values = raw[mask]
        values = values[np.isfinite(values)]

        if values.size < 8:
            return None

        return {
            "mean": float(np.mean(values)),
            "std": float(np.std(values)),
            "count": int(values.size),
        }
    except Exception:
        return None

def _module1_v10_detect_small_edge_bbs(
    raw: np.ndarray,
    phantom_cx: float,
    phantom_cy: float,
    phantom_radius: float,
) -> list[dict[str, Any]]:
    """
    Detect the small cardinal BBs near the outside edge of the Module 1 slice.

    Wanted pattern:
        top BB
        bottom BB
        left BB
        right BB
    """
    if cv2 is None:
        return []

    image_8bit = _normalize_to_uint8(raw)

    clahe = cv2.createCLAHE(
        clipLimit=3.0,
        tileGridSize=(8, 8),
    )
    enhanced = clahe.apply(image_8bit)

    blurred = cv2.GaussianBlur(
        enhanced,
        (5, 5),
        1.1,
    )

    height, width = raw.shape
    min_dim = min(height, width)

    min_radius = max(2, int(round(min_dim * 0.004)))
    max_radius = max(min_radius + 2, int(round(min_dim * 0.032)))
    min_dist = max(10, int(round(min_dim * 0.030)))

    raw_circles = cv2.HoughCircles(
        blurred,
        cv2.HOUGH_GRADIENT,
        dp=1.1,
        minDist=min_dist,
        param1=38,
        param2=8,
        minRadius=min_radius,
        maxRadius=max_radius,
    )

    if raw_circles is None:
        return []

    candidates: list[dict[str, Any]] = []

    for x_value, y_value, radius in raw_circles[0, :]:
        x_float = float(x_value)
        y_float = float(y_value)
        r_float = float(radius)

        dx = x_float - float(phantom_cx)
        dy = y_float - float(phantom_cy)
        distance = math.hypot(dx, dy)
        ratio = distance / max(float(phantom_radius), 1e-6)

        # These are edge BBs, not the large material inserts.
        if ratio < 0.55 or ratio > 1.10:
            continue

        if r_float > float(phantom_radius) * 0.075:
            continue

        # Ignore pure noise: the BB should have measurable local contrast/noise.
        stats = _module1_v10_basic_roi_stats(
            raw=raw,
            cx=x_float,
            cy=y_float,
            radius_pixels=max(3.0, r_float),
        )

        if stats is None:
            continue

        angle = (math.degrees(math.atan2(dy, dx)) + 360.0) % 360.0

        candidates.append({
            "x": x_float,
            "y": y_float,
            "radius": r_float,
            "distanceRatio": ratio,
            "angleDegrees": angle,
            "meanHU": round(float(stats["mean"]), 2),
            "stdHU": round(float(stats["std"]), 2),
        })

    # Merge Hough duplicates.
    merged: list[dict[str, Any]] = []

    for candidate in sorted(candidates, key=lambda item: float(item["radius"]), reverse=True):
        duplicate = False

        for kept in merged:
            if math.hypot(
                float(candidate["x"]) - float(kept["x"]),
                float(candidate["y"]) - float(kept["y"]),
            ) < max(float(candidate["radius"]), float(kept["radius"])) * 2.2:
                duplicate = True
                break

        if not duplicate:
            merged.append(candidate)

    return sorted(
        merged,
        key=lambda item: abs(float(item["distanceRatio"]) - 0.84),
    )[:10]

def _module1_v10_cardinal_slot_for_bb(
    bb: dict[str, Any],
    phantom_cx: float,
    phantom_cy: float,
) -> tuple[str, float]:
    dx = float(bb["x"]) - float(phantom_cx)
    dy = float(bb["y"]) - float(phantom_cy)

    # Image coordinates: y smaller = top, y larger = bottom.
    if abs(dx) >= abs(dy):
        if dx < 0:
            slot = "left"
            ideal_angle = 180.0
        else:
            slot = "right"
            ideal_angle = 0.0
    else:
        if dy < 0:
            slot = "top"
            ideal_angle = 270.0
        else:
            slot = "bottom"
            ideal_angle = 90.0

    angle = float(bb["angleDegrees"])
    angular_error = abs(((angle - ideal_angle + 180.0) % 360.0) - 180.0)

    return slot, float(angular_error)

def _module1_v10_cardinal_edge_bb_score(
    raw: np.ndarray,
    phantom_cx: float,
    phantom_cy: float,
    phantom_radius: float,
) -> tuple[float, dict[str, Any]]:
    bbs = _module1_v10_detect_small_edge_bbs(
        raw=raw,
        phantom_cx=phantom_cx,
        phantom_cy=phantom_cy,
        phantom_radius=phantom_radius,
    )

    slots: dict[str, dict[str, Any]] = {}

    for bb in bbs:
        slot, angular_error = _module1_v10_cardinal_slot_for_bb(
            bb=bb,
            phantom_cx=phantom_cx,
            phantom_cy=phantom_cy,
        )

        radial_error = abs(float(bb["distanceRatio"]) - 0.84)
        candidate_score = angular_error * 1.8 + radial_error * 85.0

        chosen = {
            **bb,
            "slot": slot,
            "angularError": round(float(angular_error), 3),
            "radialError": round(float(radial_error), 4),
            "slotFitScore": round(float(candidate_score), 3),
        }

        if slot not in slots or candidate_score < float(slots[slot]["slotFitScore"]):
            slots[slot] = chosen

    wanted_slots = ["top", "bottom", "left", "right"]
    slot_count = sum(1 for slot in wanted_slots if slot in slots)

    if slot_count == 4:
        slot_score = 220.0
    elif slot_count == 3:
        slot_score = 110.0
    elif slot_count == 2:
        slot_score = 40.0
    elif slot_count == 1:
        slot_score = 10.0
    else:
        slot_score = 0.0

    selected_bbs = [slots[slot] for slot in wanted_slots if slot in slots]

    if selected_bbs:
        mean_angular_error = float(np.mean([float(bb["angularError"]) for bb in selected_bbs]))
        mean_radial_error = float(np.mean([float(bb["radialError"]) for bb in selected_bbs]))

        alignment_score = max(0.0, 80.0 - mean_angular_error * 2.2)
        radial_score = max(0.0, 45.0 - mean_radial_error * 160.0)
    else:
        mean_angular_error = 999.0
        mean_radial_error = 999.0
        alignment_score = 0.0
        radial_score = 0.0

    total_score = float(slot_score + alignment_score + radial_score)

    details = {
        "method": "cardinal edge BB pattern: top, bottom, left, right",
        "edgeBbRawCandidateCount": int(len(bbs)),
        "cardinalSlotCount": int(slot_count),
        "cardinalSlotsPresent": [slot for slot in wanted_slots if slot in slots],
        "missingCardinalSlots": [slot for slot in wanted_slots if slot not in slots],
        "meanAngularError": round(float(mean_angular_error), 3),
        "meanRadialError": round(float(mean_radial_error), 4),
        "cardinalEdgeBbScore": round(float(total_score), 3),
        "selectedEdgeBbs": selected_bbs,
        "rawEdgeBbCandidates": bbs,
    }

    return total_score, details

def _module1_score_candidate_slice(
    index: int,
    raw: np.ndarray,
    classification: dict[str, Any],
) -> dict[str, Any]:
    """
    V10 Module 1 analysis slice score.

    This brings the same cardinal edge-BB idea used in Split Modules into the
    Analyze Module 1 button.
    """
    phantom_cx, phantom_cy, phantom_radius = _estimate_phantom_geometry(raw)

    circles, detection_info = _detect_insert_circles(
        raw=raw,
        phantom_cx=phantom_cx,
        phantom_cy=phantom_cy,
        phantom_radius=phantom_radius,
    )

    insert_count = len(circles)
    classifier_score = _module1_v10_classifier_score_for_index(
        classification,
        index,
    )

    if circles:
        radii = np.asarray(
            [circle[2] for circle in circles],
            dtype=np.float32,
        )
        radius_cv = float(
            np.std(radii)
            / max(float(np.mean(radii)), 1e-6)
        )
    else:
        radius_cv = 9.0

    if insert_count == 4:
        four_insert_bonus = 115.0
    elif insert_count == 5:
        four_insert_bonus = 65.0
    elif insert_count == 3:
        four_insert_bonus = 45.0
    else:
        four_insert_bonus = max(
            0.0,
            25.0 - abs(insert_count - 4) * 14.0,
        )

    cardinal_score, cardinal_details = _module1_v10_cardinal_edge_bb_score(
        raw=raw,
        phantom_cx=phantom_cx,
        phantom_cy=phantom_cy,
        phantom_radius=phantom_radius,
    )

    score = (
        cardinal_score * 1.60
        + four_insert_bonus
        + min(insert_count, 4) * 14.0
        + classifier_score * 0.25
        - radius_cv * 28.0
    )

    result = {
        "sliceIndex": int(index),
        "sliceNumber": int(index) + 1,
        "score": round(float(score), 3),
        "detectedCircleCount": int(insert_count),
        "classifierScore": round(float(classifier_score), 3),
        "radiusCoefficientOfVariation": round(float(radius_cv), 4),
        "fourInsertBonus": round(float(four_insert_bonus), 3),
        "phantomCenterX": round(float(phantom_cx), 3),
        "phantomCenterY": round(float(phantom_cy), 3),
        "phantomRadius": round(float(phantom_radius), 3),
        "detection": detection_info,
        "circles": circles,
    }

    result.update(cardinal_details)

    return result

def _choose_best_module1_slice_by_four_circles(
    slices: list[dict[str, Any]],
    classification: dict[str, Any],
) -> tuple[
    int,
    dict[str, Any] | None,
    dict[str, Any] | None,
    list[dict[str, Any]],
    list[str],
]:
    warnings: list[str] = []

    candidate_indices = _module1_v10_candidate_indices(
        classification=classification,
        slice_count=len(slices),
    )

    scored_candidates: list[dict[str, Any]] = []

    for index in candidate_indices:
        selected = slices[index]
        info = selected.get("info", {})

        if info.get("isColorDicom"):
            continue

        raw = np.asarray(selected["pixels"], dtype=np.float32)

        if raw.ndim != 2:
            continue

        try:
            scored_candidates.append(
                _module1_score_candidate_slice(
                    index=index,
                    raw=raw,
                    classification=classification,
                )
            )
        except Exception as exc:
            scored_candidates.append({
                "sliceIndex": int(index),
                "sliceNumber": int(index) + 1,
                "score": -9999.0,
                "detectedCircleCount": 0,
                "cardinalSlotCount": 0,
                "error": str(exc),
            })

    scored_candidates = sorted(
        scored_candidates,
        key=lambda item: (
            float(item.get("cardinalSlotCount", 0)),
            float(item.get("cardinalEdgeBbScore", 0.0)),
            float(item.get("detectedCircleCount", 0)),
            float(item.get("score", -9999.0)),
        ),
        reverse=True,
    )

    if not scored_candidates:
        warnings.append(
            "No valid Module 1 candidate slice could be scored. Using the first slice as fallback."
        )
        return (
            0,
            _module1_v10_slice_record_for_index(classification, 0),
            _module1_v10_group_for_index(classification, 0),
            [],
            warnings,
        )

    best = scored_candidates[0]
    best_index = int(best["sliceIndex"])

    if int(best.get("cardinalSlotCount", 0)) < 4:
        warnings.append(
            "The selected Module 1 slice did not show all four cardinal edge BBs "
            "(top, bottom, left, right). Using the strongest available candidate for now."
        )

    return (
        best_index,
        _module1_v10_slice_record_for_index(classification, best_index),
        _module1_v10_group_for_index(classification, best_index),
        scored_candidates,
        warnings,
    )

def _m1v12_stats(raw, cx, cy, radius):
    mask = _ellipse_mask_pixels(raw.shape, cx, cy, radius, radius)
    values = raw[mask]
    values = values[np.isfinite(values)]
    if values.size < 12:
        return None
    return {
        "mean": float(np.mean(values)),
        "std": float(np.std(values)),
        "count": int(values.size),
    }

def _m1v12_detect_insert_rois(raw, phantom_cx, phantom_cy, phantom_radius):
    """
    Detect Module 1 material inserts as large circles.
    This avoids V11 connected-component thresholding that could grab wrong patches.
    """
    circles, info = _detect_insert_circles(
        raw=raw,
        phantom_cx=phantom_cx,
        phantom_cy=phantom_cy,
        phantom_radius=phantom_radius,
    )

    candidates = []

    for x, y, r in circles:
        x = float(x)
        y = float(y)
        r = float(r)
        d = math.hypot(x - phantom_cx, y - phantom_cy)
        ratio = d / max(float(phantom_radius), 1e-6)

        # Inserts should be mid-phantom circles, not cardinal edge BBs and not center water.
        if ratio < 0.16 or ratio > 0.70:
            continue

        roi_r = max(4.0, r * 0.50)
        stats = _m1v12_stats(raw, x, y, roi_r)
        if not stats:
            continue

        mean_hu = float(stats["mean"])
        sd_hu = float(stats["std"])
        label, short_label, priority = _m1v12_label(mean_hu)

        # Do not accept water-like circles as material insert ROIs.
        if priority == 99 and abs(mean_hu) < 35:
            continue

        # Prefer the true material insert ring and HU that is clearly not water.
        ring_error = abs(ratio - 0.43)
        hu_strength = min(1.0, abs(mean_hu) / 1000.0)
        score = ring_error * 120.0 + min(sd_hu, 120.0) * 0.10 - hu_strength * 22.0

        candidates.append({
            "label": label,
            "shortLabel": short_label,
            "priority": int(priority),
            "x": round(x, 3),
            "y": round(y, 3),
            "radius": round(r, 3),
            "roiRadius": round(roi_r, 3),
            "meanHU": round(mean_hu, 2),
            "stdHU": round(sd_hu, 2),
            "distanceRatio": round(ratio, 4),
            "score": round(float(score), 3),
            "method": "large Hough circle + HU label",
        })

    # Choose one per expected material if possible.
    chosen = []
    for priority in [0, 1, 2, 3]:
        matches = [c for c in candidates if int(c.get("priority", 99)) == priority]
        if matches:
            chosen.append(sorted(matches, key=lambda c: float(c["score"]))[0])

    # Fill missing categories with best remaining circles, but avoid duplicates.
    for cand in sorted(candidates, key=lambda c: float(c["score"])):
        if len(chosen) >= 4:
            break
        duplicate = False
        for kept in chosen:
            if math.hypot(float(cand["x"]) - float(kept["x"]), float(cand["y"]) - float(kept["y"])) < max(float(cand["radius"]), float(kept["radius"])) * 1.1:
                duplicate = True
                break
        if not duplicate:
            chosen.append(cand)

    chosen = chosen[:4]

    return chosen, {
        "method": "large Hough circles filtered to material insert ring, then labeled by measured HU",
        "rawCircleCount": int(len(circles)),
        "candidateCount": int(len(candidates)),
        "chosenCount": int(len(chosen)),
        "chosenLabels": [c["label"] for c in chosen],
        "sourceHoughDiagnostics": info,
        "candidates": candidates[:12],
    }

def _m1v12_flag(roi):
    band = _m1v12_band(str(roi["label"]))
    roi["temporaryExpectedRange"] = band
    if band["low"] is None or band["high"] is None:
        roi["quickFlag"] = "MEASURED"
    elif float(band["low"]) <= float(roi["meanHU"]) <= float(band["high"]):
        roi["quickFlag"] = "OK"
    else:
        roi["quickFlag"] = "CHECK"
    return roi

def _m1v13_radius_for_area_mm2(
    area_mm2: float,
    row_spacing_mm: float,
    col_spacing_mm: float,
    min_radius_pixels: float = 4.0,
    max_radius_pixels: float | None = None,
) -> float:
    """
    Convert target physical ROI area to pixel radius.

    area = pi * rx * ry * row_spacing * col_spacing
    Here rx = ry = radius_pixels.
    """
    pixel_area_mm2 = max(float(row_spacing_mm) * float(col_spacing_mm), 1e-6)
    radius_pixels = math.sqrt(float(area_mm2) / (math.pi * pixel_area_mm2))

    radius_pixels = max(float(min_radius_pixels), radius_pixels)

    if max_radius_pixels is not None:
        radius_pixels = min(radius_pixels, float(max_radius_pixels))

    return float(radius_pixels)

def _m1v12_label(mean_hu):
    """
    V15 label override.
    Rename the low-density material insert to Polyethylene.
    """
    if mean_hu <= -500:
        return "Air", "Air", 0
    if -350 < mean_hu <= -35:
        return "Polyethylene", "Polyethylene", 1
    if 40 <= mean_hu <= 260:
        return "Acrylic / PMMA-like insert", "Acrylic", 2
    if mean_hu >= 300:
        return "Bone / high-density insert", "Bone", 3
    return "Detected insert", "Insert", 99

def _m1v12_band(label):
    """
    V15 temporary review-band override.
    Low-density is now reported as Polyethylene.
    """
    text = str(label or "")
    lower = text.lower()

    if text.startswith("Water"):
        return {"low": -7, "high": 7, "name": "Water approx 0 HU"}
    if "air" in lower:
        return {"low": -1040, "high": -950, "name": "Air approx -1000 HU"}
    if "polyethylene" in lower or "low-density" in lower or "low density" in lower:
        return {"low": -150, "high": -40, "name": "Polyethylene rough band"}
    if "acrylic" in lower or "pmma" in lower:
        return {"low": 90, "high": 150, "name": "Acrylic/PMMA rough band"}
    if "bone" in lower or "high-density" in lower or "high density" in lower:
        return {"low": 700, "high": 1100, "name": "Bone/high-density rough band"}
    return {"low": None, "high": None, "name": "Measured only"}

def _m1v15_roi_values(raw, cx, cy, radius):
    mask = _ellipse_mask_pixels(
        raw.shape,
        float(cx),
        float(cy),
        float(radius),
        float(radius),
    )
    values = raw[mask]
    values = values[np.isfinite(values)]

    if values.size < 12:
        return None

    return values

def _m1v18_line_bar_components(raw, phantom_cx, phantom_cy, phantom_radius, inserts, water_radius):
    """
    Detect the line-pair/bar regions first so water detection cannot count them.

    These are the striped horizontal bar groups near the middle column of
    Module 1. They are high-texture/high-gradient, horizontally elongated,
    and should be treated as forbidden regions for water ROI detection.
    """
    try:
        import cv2 as _cv2
    except Exception:
        return np.zeros(raw.shape, dtype=bool), [], {
            "method": "OpenCV unavailable; line-bar mask disabled",
            "componentCount": 0,
        }

    arr = np.asarray(raw, dtype=np.float32)
    finite = arr[np.isfinite(arr)]

    if finite.size < 200:
        return np.zeros(raw.shape, dtype=bool), [], {
            "method": "not enough finite pixels; line-bar mask disabled",
            "componentCount": 0,
        }

    h, w = arr.shape
    yy, xx = np.ogrid[:h, :w]

    r = float(phantom_radius)
    cx0 = float(phantom_cx)
    cy0 = float(phantom_cy)

    inside = ((xx - cx0) ** 2 + (yy - cy0) ** 2) <= (r * 0.78) ** 2

    # Exclude material inserts before texture detection so insert edges do not
    # become "line bars."
    insert_mask = np.zeros(arr.shape, dtype=bool)

    for insert in inserts or []:
        ix = float(insert.get("x", 0.0))
        iy = float(insert.get("y", 0.0))
        ir = float(insert.get("radius", water_radius))
        insert_mask |= ((xx - ix) ** 2 + (yy - iy) ** 2) <= (ir + water_radius * 1.60) ** 2

    # The line-pair bars live in the central column region, not near the
    # material insert ring. Keep this broad enough for rotated/slightly shifted
    # images, but still not the whole phantom.
    central_column = (
        (np.abs(xx - cx0) <= r * 0.30)
        & (np.abs(yy - cy0) <= r * 0.58)
    )

    search_mask = inside & central_column & (~insert_mask)

    lo = float(np.percentile(finite, 1.0))
    hi = float(np.percentile(finite, 99.0))

    if hi <= lo:
        return np.zeros(raw.shape, dtype=bool), [], {
            "method": "flat image; line-bar mask disabled",
            "componentCount": 0,
        }

    clipped = np.clip(arr, lo, hi).astype(np.float32)

    # Local texture and horizontal-bar response.
    k = int(max(5, round(float(water_radius) * 0.50)))
    if k % 2 == 0:
        k += 1

    mean = _cv2.blur(clipped, (k, k))
    mean_sq = _cv2.blur(clipped * clipped, (k, k))
    local_sd = np.sqrt(np.maximum(mean_sq - mean * mean, 0.0)).astype(np.float32)

    # Horizontal bars have strong changes in the vertical direction.
    grad_y = _cv2.Sobel(clipped, _cv2.CV_32F, 0, 1, ksize=3)
    grad_x = _cv2.Sobel(clipped, _cv2.CV_32F, 1, 0, ksize=3)
    horiz_response = np.abs(grad_y) - 0.45 * np.abs(grad_x)

    sd_values = local_sd[search_mask & np.isfinite(local_sd)]
    response_values = horiz_response[search_mask & np.isfinite(horiz_response)]

    if sd_values.size < 50 or response_values.size < 50:
        return np.zeros(raw.shape, dtype=bool), [], {
            "method": "not enough central texture pixels; line-bar mask disabled",
            "componentCount": 0,
        }

    sd_threshold = max(
        float(np.percentile(sd_values, 80.0)),
        float(np.median(sd_values) + np.std(sd_values) * 0.55),
    )
    response_threshold = max(
        float(np.percentile(response_values, 80.0)),
        float(np.median(response_values) + np.std(response_values) * 0.55),
    )

    raw_bar_mask = search_mask & (
        (local_sd >= sd_threshold)
        | (horiz_response >= response_threshold)
    )

    kernel = _cv2.getStructuringElement(_cv2.MORPH_RECT, (7, 3))
    raw_bar_mask = _cv2.morphologyEx(raw_bar_mask.astype(np.uint8), _cv2.MORPH_CLOSE, kernel)
    raw_bar_mask = _cv2.morphologyEx(raw_bar_mask.astype(np.uint8), _cv2.MORPH_OPEN, kernel)

    count, labels, stats, centroids = _cv2.connectedComponentsWithStats(
        raw_bar_mask.astype(np.uint8),
        connectivity=8,
    )

    bars = []
    final_mask = np.zeros(arr.shape, dtype=bool)

    min_area = max(12.0, (water_radius * water_radius) * 0.10)
    max_area = (r * r) * 0.08

    for component_id in range(1, count):
        area = float(stats[component_id, _cv2.CC_STAT_AREA])

        if area < min_area or area > max_area:
            continue

        x = float(stats[component_id, _cv2.CC_STAT_LEFT])
        y = float(stats[component_id, _cv2.CC_STAT_TOP])
        width = float(stats[component_id, _cv2.CC_STAT_WIDTH])
        height = float(stats[component_id, _cv2.CC_STAT_HEIGHT])

        if width <= 0 or height <= 0:
            continue

        aspect = width / max(height, 1.0)

        # A line-bar group should be wider than tall. Allow relaxed aspect
        # because the bars can break into chunks after thresholding.
        if aspect < 1.15:
            continue

        center_x = float(centroids[component_id][0])
        center_y = float(centroids[component_id][1])

        # Stay close to central column and not phantom edge.
        if abs(center_x - cx0) > r * 0.35:
            continue

        if abs(center_y - cy0) > r * 0.62:
            continue

        component_mask = labels == component_id

        # Dilate by at least the ROI radius so a water ROI cannot overlap a bar.
        dilate_radius = int(max(4, round(float(water_radius) * 1.20)))
        dilate_kernel = _cv2.getStructuringElement(
            _cv2.MORPH_ELLIPSE,
            (dilate_radius * 2 + 1, dilate_radius * 2 + 1),
        )
        dilated = _cv2.dilate(component_mask.astype(np.uint8), dilate_kernel, iterations=1).astype(bool)

        final_mask |= dilated

        bars.append({
            "x": round(x, 2),
            "y": round(y, 2),
            "width": round(width, 2),
            "height": round(height, 2),
            "cx": round(center_x, 2),
            "cy": round(center_y, 2),
            "areaPixels": int(area),
            "aspectRatio": round(float(aspect), 3),
        })

    diagnostics = {
        "method": "central-column high-texture horizontal-bar detector",
        "componentCount": int(len(bars)),
        "sdThreshold": round(float(sd_threshold), 3),
        "horizontalResponseThreshold": round(float(response_threshold), 3),
        "kernelSize": int(k),
        "rawBarPixelCount": int(np.sum(raw_bar_mask)),
        "finalExcludedPixelCount": int(np.sum(final_mask)),
        "bars": bars,
    }

    return final_mask, bars, diagnostics

def _m1v21_insert_text(insert):
    return (str(insert.get("label", "")) + " " + str(insert.get("shortLabel", ""))).lower()

def _m1v21_expected_water_zone(phantom_cx, phantom_cy, phantom_radius, inserts):
    """
    Expected search zone only. The final location still comes from the detected
    faint outer circle.
    """
    poly = None
    acrylic = None

    for item in inserts or []:
        text = _m1v21_insert_text(item)

        if poly is None and ("polyethylene" in text or "low-density" in text or "low density" in text):
            poly = item

        if acrylic is None and ("acrylic" in text or "pmma" in text):
            acrylic = item

    if poly is not None and acrylic is not None:
        left_x = (float(poly["x"]) + float(acrylic["x"])) / 2.0
        left_y = (float(poly["y"]) + float(acrylic["y"])) / 2.0

        # Water is left-middle / central-left relative to this left insert column.
        target_x = left_x - float(phantom_radius) * 0.12
        target_y = left_y
        anchor = "left/central-left of Polyethylene-Acrylic column"
    else:
        target_x = float(phantom_cx) - float(phantom_radius) * 0.32
        target_y = float(phantom_cy)
        anchor = "fallback left-middle layout"

    return {
        "x": round(float(target_x), 3),
        "y": round(float(target_y), 3),
        "anchor": anchor,
    }

def _m1v21_make_circle_maps(raw):
    try:
        import cv2 as _cv2
    except Exception:
        return None, None, {"method": "OpenCV unavailable"}

    arr = np.asarray(raw, dtype=np.float32)
    finite = arr[np.isfinite(arr)]

    if finite.size < 100:
        return None, None, {"method": "not enough finite pixels"}

    low = float(np.percentile(finite, 0.8))
    high = float(np.percentile(finite, 99.2))

    if high <= low:
        return None, None, {"method": "flat image"}

    clipped = np.clip(arr, low, high)
    img = ((clipped - low) / (high - low) * 255.0).astype(np.uint8)

    clahe = _cv2.createCLAHE(clipLimit=4.0, tileGridSize=(8, 8))
    enhanced = clahe.apply(img)

    # DoG specifically helps the weak/faded circular boundary.
    small = _cv2.GaussianBlur(enhanced, (5, 5), 0)
    large = _cv2.GaussianBlur(enhanced, (35, 35), 0)
    dog = _cv2.absdiff(small, large)
    dog = _cv2.normalize(dog, None, 0, 255, _cv2.NORM_MINMAX).astype(np.float32)

    gx = _cv2.Sobel(enhanced, _cv2.CV_32F, 1, 0, ksize=3)
    gy = _cv2.Sobel(enhanced, _cv2.CV_32F, 0, 1, ksize=3)
    grad = np.sqrt(gx * gx + gy * gy).astype(np.float32)

    return dog, grad, {
        "method": "CLAHE + DoG + Sobel for faint water outer circle",
        "clipLow": round(float(low), 3),
        "clipHigh": round(float(high), 3),
    }

def _m1v21_circle_mask(shape, cx, cy, radius):
    yy, xx = np.ogrid[:shape[0], :shape[1]]
    return ((xx - float(cx)) ** 2 + (yy - float(cy)) ** 2) <= float(radius) ** 2

def _m1v21_ring_mask(shape, cx, cy, inner_radius, outer_radius):
    yy, xx = np.ogrid[:shape[0], :shape[1]]
    dist2 = (xx - float(cx)) ** 2 + (yy - float(cy)) ** 2
    return (dist2 >= float(inner_radius) ** 2) & (dist2 <= float(outer_radius) ** 2)

def _m1v21_arc_score(edge_map, cx, cy, radius):
    """
    Looks for partial arcs, not a full strong circle. The water circle is faint
    and may only be partly visible.
    """
    if edge_map is None:
        return {
            "ringMean": 0.0,
            "insideMean": 0.0,
            "partialArcCount": 0,
            "arcScore": 0.0,
        }

    ring = _m1v21_ring_mask(edge_map.shape, cx, cy, radius * 0.86, radius * 1.18)
    inside = _m1v21_circle_mask(edge_map.shape, cx, cy, radius * 0.55)

    ring_values = edge_map[ring]
    inside_values = edge_map[inside]

    if ring_values.size < 10 or inside_values.size < 10:
        return {
            "ringMean": 0.0,
            "insideMean": 0.0,
            "partialArcCount": 0,
            "arcScore": 0.0,
        }

    ring_mean = float(np.mean(ring_values))
    inside_mean = float(np.mean(inside_values))

    yy, xx = np.ogrid[:edge_map.shape[0], :edge_map.shape[1]]
    angles = (np.degrees(np.arctan2(yy - float(cy), xx - float(cx))) + 360.0) % 360.0

    arc_means = []

    for start in range(0, 360, 30):
        end = start + 30
        if end <= 360:
            arc_mask = ring & (angles >= start) & (angles < end)
        else:
            arc_mask = ring & ((angles >= start) | (angles < (end - 360)))

        values = edge_map[arc_mask]
        arc_means.append(float(np.mean(values)) if values.size else 0.0)

    baseline = inside_mean + max(2.0, float(np.std(arc_means)) * 0.10)
    partial_count = int(sum(1 for value in arc_means if value > baseline))

    # Reward faint partial ring more than solid texture.
    arc_score = max(0.0, ring_mean - inside_mean * 0.55) + partial_count * 2.8

    return {
        "ringMean": round(float(ring_mean), 3),
        "insideMean": round(float(inside_mean), 3),
        "partialArcCount": int(partial_count),
        "arcScore": round(float(arc_score), 3),
        "arcMeans": [round(float(v), 3) for v in arc_means],
    }

def _m1v21_roi_stats(raw, cx, cy, radius):
    values = _m1v15_roi_values(raw, cx, cy, radius)

    if values is None:
        return None

    return {
        "mean": float(np.mean(values)),
        "std": float(np.std(values)),
        "count": int(values.size),
    }

def _m1v21_overlaps_insert(cx, cy, radius, inserts, safety=1.00):
    for insert in inserts or []:
        ix = float(insert.get("x", 0.0))
        iy = float(insert.get("y", 0.0))
        ir = float(insert.get("radius", radius))
        if math.hypot(float(cx) - ix, float(cy) - iy) < (float(radius) + ir) * float(safety):
            return True
    return False

def _m1v21_detect_outer_water_circle(raw, phantom_cx, phantom_cy, phantom_radius, inserts, water_roi_radius):
    """
    V33 fast corrected LARGE faint water outer-circle detector.

    This keeps the V32 target geometry, but speeds it up:
      - no broad dense search
      - predict the large faint water circle from the two left inserts
      - score only a small coarse grid near that prediction
      - fine-refine only the best few candidates
      - use local crops only

    Target:
      - large faint circle on the left side
      - center left of the two left material inserts
      - ROI is placed inside that large circle
    """
    import time

    t0 = time.perf_counter()

    dog, grad, map_diag = _m1v21_make_circle_maps(raw)

    try:
        line_bar_mask, line_bars, line_diag = _m1v18_line_bar_components(
            raw=raw,
            phantom_cx=phantom_cx,
            phantom_cy=phantom_cy,
            phantom_radius=phantom_radius,
            inserts=inserts,
            water_radius=water_roi_radius,
        )
    except Exception as exc:
        line_bar_mask = np.zeros(raw.shape, dtype=bool)
        line_bars = []
        line_diag = {"error": str(exc)}

    h, w = raw.shape

    valid_inserts = []
    for item in inserts or []:
        try:
            x = float(item.get("x", 0.0))
            y = float(item.get("y", 0.0))
            r = float(item.get("radius", 0.0))
            if r > 2.0:
                valid_inserts.append({"x": x, "y": y, "radius": r})
        except Exception:
            continue

    if len(valid_inserts) >= 2:
        left_pair = sorted(valid_inserts, key=lambda item: float(item["x"]))[:2]
        left_pair = sorted(left_pair, key=lambda item: float(item["y"]))
        top_left = left_pair[0]
        bottom_left = left_pair[-1]

        insert_radius = float(np.median([item["radius"] for item in valid_inserts]))
        left_insert_x = (float(top_left["x"]) + float(bottom_left["x"])) / 2.0
        left_insert_y = (float(top_left["y"]) + float(bottom_left["y"])) / 2.0

        expected_x = left_insert_x - max(insert_radius * 1.35, float(phantom_radius) * 0.145)
        expected_y = left_insert_y
        expected_outer_radius = max(insert_radius * 1.75, float(phantom_radius) * 0.22)
        expected_outer_radius = min(expected_outer_radius, float(phantom_radius) * 0.285)
    else:
        insert_radius = float(phantom_radius) * 0.105
        expected_x = float(phantom_cx) - float(phantom_radius) * 0.62
        expected_y = float(phantom_cy) + float(phantom_radius) * 0.04
        expected_outer_radius = float(phantom_radius) * 0.245

    min_outer_radius = max(10.0, expected_outer_radius * 0.84)
    max_outer_radius = min(float(phantom_radius) * 0.34, expected_outer_radius * 1.12)

    def local_values(image, cx, cy, radius, inner_scale=1.0):
        cx = float(cx)
        cy = float(cy)
        radius = float(radius) * float(inner_scale)

        x1 = max(0, int(np.floor(cx - radius - 2)))
        y1 = max(0, int(np.floor(cy - radius - 2)))
        x2 = min(image.shape[1], int(np.ceil(cx + radius + 3)))
        y2 = min(image.shape[0], int(np.ceil(cy + radius + 3)))

        if x2 <= x1 or y2 <= y1:
            return None

        crop = image[y1:y2, x1:x2]
        yy, xx = np.ogrid[y1:y2, x1:x2]
        mask = ((xx - cx) ** 2 + (yy - cy) ** 2) <= radius ** 2
        values = crop[mask]
        values = values[np.isfinite(values)]

        if values.size < 20:
            return None

        return values

    def line_overlap(cx, cy, radius):
        if line_bar_mask is None:
            return 0.0

        cx = float(cx)
        cy = float(cy)
        radius = float(radius)

        x1 = max(0, int(np.floor(cx - radius - 2)))
        y1 = max(0, int(np.floor(cy - radius - 2)))
        x2 = min(line_bar_mask.shape[1], int(np.ceil(cx + radius + 3)))
        y2 = min(line_bar_mask.shape[0], int(np.ceil(cy + radius + 3)))

        if x2 <= x1 or y2 <= y1:
            return 1.0

        yy, xx = np.ogrid[y1:y2, x1:x2]
        mask = ((xx - cx) ** 2 + (yy - cy) ** 2) <= radius ** 2

        if np.sum(mask) < 1:
            return 1.0

        return float(np.sum(line_bar_mask[y1:y2, x1:x2][mask])) / max(float(np.sum(mask)), 1.0)

    def quick_ring_score(edge_map, cx, cy, radius):
        if edge_map is None:
            return {
                "ringMean": 0.0,
                "insideMean": 0.0,
                "outsideMean": 0.0,
                "partialArcCount": 0,
                "arcScore": 0.0,
            }

        cx = float(cx)
        cy = float(cy)
        radius = float(radius)

        margin = radius * 1.24
        x1 = max(0, int(np.floor(cx - margin - 2)))
        y1 = max(0, int(np.floor(cy - margin - 2)))
        x2 = min(edge_map.shape[1], int(np.ceil(cx + margin + 3)))
        y2 = min(edge_map.shape[0], int(np.ceil(cy + margin + 3)))

        if x2 <= x1 or y2 <= y1:
            return {
                "ringMean": 0.0,
                "insideMean": 0.0,
                "outsideMean": 0.0,
                "partialArcCount": 0,
                "arcScore": 0.0,
            }

        crop = edge_map[y1:y2, x1:x2]
        yy, xx = np.ogrid[y1:y2, x1:x2]
        d = np.sqrt((xx - cx) ** 2 + (yy - cy) ** 2)

        ring = (d >= radius * 0.92) & (d <= radius * 1.08)
        inside = d <= radius * 0.70
        outside = (d >= radius * 1.14) & (d <= radius * 1.24)

        if np.sum(ring) < 30 or np.sum(inside) < 30:
            return {
                "ringMean": 0.0,
                "insideMean": 0.0,
                "outsideMean": 0.0,
                "partialArcCount": 0,
                "arcScore": 0.0,
            }

        ring_mean = float(np.mean(crop[ring]))
        inside_mean = float(np.mean(crop[inside]))
        outside_mean = float(np.mean(crop[outside])) if np.sum(outside) else 0.0

        # Much faster than full arc list: four quadrants only.
        angles = (np.degrees(np.arctan2(yy - cy, xx - cx)) + 360.0) % 360.0
        arc_values = []
        for start in (0, 90, 180, 270):
            arc = ring & (angles >= start) & (angles < start + 90)
            arc_values.append(float(np.mean(crop[arc])) if np.sum(arc) else 0.0)

        baseline = max(inside_mean, outside_mean) + 0.5
        partial_arc_count = int(sum(value > baseline for value in arc_values))

        ring_contrast = max(0.0, ring_mean - inside_mean * 0.55 - outside_mean * 0.35)
        arc_score = ring_contrast * 3.8 + partial_arc_count * 4.0

        return {
            "ringMean": round(float(ring_mean), 3),
            "insideMean": round(float(inside_mean), 3),
            "outsideMean": round(float(outside_mean), 3),
            "partialArcCount": int(partial_arc_count),
            "arcScore": round(float(arc_score), 3),
        }

    def too_close_to_material(cx, cy, radius):
        for insert in valid_inserts:
            dist = math.hypot(float(cx) - float(insert["x"]), float(cy) - float(insert["y"]))
            if dist < float(radius) * 0.48 + float(insert["radius"]) * 0.70:
                return True
        return False

    def score_candidate(cx, cy, radius, source):
        cx = float(cx)
        cy = float(cy)
        radius = float(radius)

        if cx - radius < 0 or cy - radius < 0 or cx + radius >= w or cy + radius >= h:
            return None

        if math.hypot(cx - float(phantom_cx), cy - float(phantom_cy)) + radius > float(phantom_radius) * 0.90:
            return None

        if too_close_to_material(cx, cy, radius):
            return None

        overlap_fraction = line_overlap(cx, cy, radius)
        if overlap_fraction > 0.018:
            return None

        roi_radius = min(float(water_roi_radius), radius * 0.32)
        roi_values = local_values(raw, cx, cy, roi_radius)

        if roi_values is None:
            return None

        mean_hu = float(np.mean(roi_values))
        sd_hu = float(np.std(roi_values))

        dog_arc = quick_ring_score(dog, cx, cy, radius)
        grad_arc = quick_ring_score(grad, cx, cy, radius)

        layout_distance = math.hypot(cx - expected_x, cy - expected_y)
        layout_score = max(0.0, 100.0 - (layout_distance / max(insert_radius * 1.8, 1e-6)) * 100.0)

        radius_error = abs(radius - expected_outer_radius)
        radius_score = max(0.0, 100.0 - (radius_error / max(expected_outer_radius * 0.22, 1e-6)) * 100.0)

        water_quality = max(0.0, 65.0 - abs(mean_hu) * 2.0) + max(0.0, 45.0 - sd_hu * 2.2)
        ring_score = float(dog_arc["arcScore"]) * 2.6 + float(grad_arc["arcScore"]) * 0.55
        partial_bonus = max(int(dog_arc["partialArcCount"]), int(grad_arc["partialArcCount"])) * 5.0

        quality = (
            layout_score * 1.65
            + radius_score * 0.95
            + water_quality
            + ring_score
            + partial_bonus
            - overlap_fraction * 250.0
        )

        return {
            "x": round(cx, 3),
            "y": round(cy, 3),
            "outerRadius": round(radius, 3),
            "roiRadius": round(float(roi_radius), 3),
            "quality": round(float(quality), 3),
            "layoutScore": round(float(layout_score), 3),
            "radiusScore": round(float(radius_score), 3),
            "waterQuality": round(float(water_quality), 3),
            "ringScore": round(float(ring_score), 3),
            "partialBonus": round(float(partial_bonus), 3),
            "meanHU": round(float(mean_hu), 2),
            "stdHU": round(float(sd_hu), 2),
            "lineBarOverlapFraction": round(float(overlap_fraction), 5),
            "expectedLargeCircle": {
                "x": round(float(expected_x), 3),
                "y": round(float(expected_y), 3),
                "outerRadius": round(float(expected_outer_radius), 3),
            },
            "source": source,
            "dogArc": dog_arc,
            "gradArc": grad_arc,
        }

    # Fast candidate list. This is the speed improvement over V32.
    coarse_candidates = []
    dx_values = [-14.0, -8.0, -4.0, 0.0, 4.0, 8.0, 14.0]
    dy_values = [-18.0, -10.0, -5.0, 0.0, 5.0, 10.0, 18.0]
    r_values = [
        min_outer_radius,
        expected_outer_radius * 0.92,
        expected_outer_radius,
        expected_outer_radius * 1.08,
        max_outer_radius,
    ]

    scanned = 0

    for dy in dy_values:
        for dx in dx_values:
            for radius in r_values:
                scanned += 1
                item = score_candidate(
                    expected_x + dx,
                    expected_y + dy,
                    max(min_outer_radius, min(max_outer_radius, radius)),
                    "V33 fast large-water coarse search",
                )
                if item is not None:
                    coarse_candidates.append(item)

    # Add exact layout fallback.
    fallback_item = score_candidate(expected_x, expected_y, expected_outer_radius, "V33 fast layout fallback")
    if fallback_item is not None:
        coarse_candidates.append(fallback_item)

    if not coarse_candidates:
        elapsed_ms = round((time.perf_counter() - t0) * 1000.0, 2)
        return {
            "found": False,
            "x": float(expected_x),
            "y": float(expected_y),
            "outerRadius": float(expected_outer_radius),
            "roiRadius": min(float(water_roi_radius), float(expected_outer_radius) * 0.32),
            "fallbackUsed": True,
            "expectedWaterTarget": {
                "x": round(float(expected_x), 3),
                "y": round(float(expected_y), 3),
                "outerRadius": round(float(expected_outer_radius), 3),
                "targetType": "large faint water outer circle",
            },
            "candidateCount": 0,
            "scannedCandidateCount": int(scanned),
            "elapsedMs": elapsed_ms,
            "speedMode": "V33 fast corrected large faint water outer-circle detector",
            "mapDiagnostics": map_diag,
            "lineBarDiagnostics": line_diag,
        }

    coarse_candidates = sorted(coarse_candidates, key=lambda item: float(item["quality"]), reverse=True)[:5]

    refined = list(coarse_candidates)
    fine_xy = [-2.0, -1.0, 0.0, 1.0, 2.0]
    fine_r = [-1.5, 0.0, 1.5]
    seen = set()

    for seed in coarse_candidates[:4]:
        sx = float(seed["x"])
        sy = float(seed["y"])
        sr = float(seed["outerRadius"])

        for dy in fine_xy:
            for dx in fine_xy:
                for dr in fine_r:
                    x = sx + dx
                    y = sy + dy
                    radius = max(float(min_outer_radius), min(float(max_outer_radius), sr + dr))

                    key = (int(round(x * 2.0)), int(round(y * 2.0)), int(round(radius * 2.0)))
                    if key in seen:
                        continue
                    seen.add(key)

                    scanned += 1
                    item = score_candidate(x, y, radius, "V33 fast large-water fine search")
                    if item is not None:
                        refined.append(item)

    refined = sorted(refined, key=lambda item: float(item["quality"]), reverse=True)
    best = refined[0]

    elapsed_ms = round((time.perf_counter() - t0) * 1000.0, 2)

    return {
        "found": True,
        "x": float(best["x"]),
        "y": float(best["y"]),
        "outerRadius": float(best["outerRadius"]),
        "roiRadius": float(best["roiRadius"]),
        "fallbackUsed": False,
        "expectedWaterTarget": {
            "x": round(float(expected_x), 3),
            "y": round(float(expected_y), 3),
            "outerRadius": round(float(expected_outer_radius), 3),
            "targetType": "large faint water outer circle left of left material inserts",
        },
        "bestCandidate": best,
        "topCandidates": refined[:10],
        "candidateCount": int(len(refined)),
        "scannedCandidateCount": int(scanned),
        "elapsedMs": elapsed_ms,
        "speedMode": "V33 fast corrected large faint water outer-circle detector",
        "mapDiagnostics": map_diag,
        "lineBarDiagnostics": line_diag,
    }

def _m1v12_find_water(raw, phantom_cx, phantom_cy, phantom_radius, inserts, water_radius):
    detected = _m1v21_detect_outer_water_circle(
        raw=raw,
        phantom_cx=phantom_cx,
        phantom_cy=phantom_cy,
        phantom_radius=phantom_radius,
        inserts=inserts,
        water_roi_radius=water_radius,
    )

    roi_radius = float(detected.get("roiRadius", water_radius))
    cx = float(detected["x"])
    cy = float(detected["y"])

    stats = _m1v21_roi_stats(raw, cx, cy, roi_radius) or {
        "mean": 0.0,
        "std": 0.0,
        "count": 0,
    }

    return {
        "cx": round(cx, 3),
        "cy": round(cy, 3),
        "radius": round(float(roi_radius), 3),
        "detectedWaterCircleRadius": round(float(detected.get("outerRadius", roi_radius)), 3),
        "method": "V21 detected faint outer water circle first, then placed ROI inside it",
        "fallbackUsed": bool(detected.get("fallbackUsed", False)),
        "meanHU": round(float(stats["mean"]), 2),
        "stdHU": round(float(stats["std"]), 2),
        "pixelCount": int(stats["count"]),
        "outerWaterCircle": detected,
    }

def create_module1_ct_number_analysis(
    stack_id: str | None = None,
    uploaded_file=None,
    window_width: float = 400,
    window_level: float = 40,
    classification_result: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """
    V21 full backend override so the overlay can show:
      - large detected faint water circle
      - smaller ROI inside it
    """
    if cv2 is None:
        raise RuntimeError(
            "OpenCV cv2 is required for Module 1 analysis. "
            "Install the opencv-python dependency."
        )

    slices = _get_slices_from_stack_or_upload(stack_id=stack_id, uploaded_file=uploaded_file)

    if not slices:
        raise ValueError("No DICOM slices were loaded.")

    if classification_result is None:
        classification_result = create_acr_module_classification(
            stack_id=stack_id,
            uploaded_file=uploaded_file,
            max_size=160,
        )

    slice_index, slice_record, module1_group, slice_candidates, warnings = _choose_best_module1_slice_by_four_circles(
        slices=slices,
        classification=classification_result,
    )

    selected = slices[slice_index]
    info = selected.get("info", {})

    if info.get("isColorDicom"):
        raise ValueError(
            "The selected DICOM is color/secondary-capture data. Module 1 HU measurements require original grayscale CT DICOM."
        )

    raw = np.asarray(selected["pixels"], dtype=np.float32)

    if raw.ndim != 2:
        raise ValueError(f"Expected a 2D CT slice, got shape {raw.shape}.")

    row_spacing = _require_number(info.get("pixelSpacingRow"), "DICOM PixelSpacing row value")
    col_spacing = _require_number(info.get("pixelSpacingCol"), "DICOM PixelSpacing column value")

    phantom_cx, phantom_cy, phantom_radius = _estimate_phantom_geometry(raw)

    inserts, insert_detection = _m1v12_detect_insert_rois(raw, phantom_cx, phantom_cy, phantom_radius)

    rois = []

    for i, insert in enumerate(inserts, start=1):
        x = float(insert["x"])
        y = float(insert["y"])
        detected_radius = float(insert["radius"])

        material_roi_radius = _m1v13_radius_for_area_mm2(
            area_mm2=M1_V13_MATERIAL_ROI_AREA_MM2,
            row_spacing_mm=row_spacing,
            col_spacing_mm=col_spacing,
            min_radius_pixels=4.0,
            max_radius_pixels=max(4.0, detected_radius * 0.55),
        )

        label = str(insert["label"])
        if "Low-density" in label or "low-density" in label or "Low density" in label:
            label = "Polyethylene"

        roi = _measure_roi(
            raw=raw,
            label=label,
            cx=x,
            cy=y,
            radius_x_pixels=material_roi_radius,
            radius_y_pixels=material_roi_radius,
            row_spacing=row_spacing,
            col_spacing=col_spacing,
            display_radius_pixels=material_roi_radius,
            full_detected_radius_pixels=detected_radius,
        )

        short_label = str(insert.get("shortLabel", label))
        if "Low" in short_label or "low" in short_label:
            short_label = "Polyethylene"

        roi["shortLabel"] = short_label
        roi["circleNumber"] = int(i)
        roi["detectionMethod"] = str(insert.get("method", "large Hough circle + HU label"))
        roi["targetAreaMm2"] = M1_V13_MATERIAL_ROI_AREA_MM2
        roi["areaPolicy"] = "physical-area ROI capped inside detected insert circle"
        roi = _m1v12_flag(roi)
        rois.append(roi)

    if len(inserts) < 4:
        warnings.append(f"Only {len(inserts)} material insert ROI(s) were detected. Review the overlay.")

    requested_water_roi_radius = _m1v13_radius_for_area_mm2(
        area_mm2=M1_V13_WATER_ROI_AREA_MM2,
        row_spacing_mm=row_spacing,
        col_spacing_mm=col_spacing,
        min_radius_pixels=5.0,
        max_radius_pixels=phantom_radius * 0.16,
    )

    water = _m1v12_find_water(raw, phantom_cx, phantom_cy, phantom_radius, inserts, requested_water_roi_radius)
    water_roi_radius = float(water["radius"])

    water_roi = _measure_roi(
        raw=raw,
        label="Water / background",
        cx=float(water["cx"]),
        cy=float(water["cy"]),
        radius_x_pixels=water_roi_radius,
        radius_y_pixels=water_roi_radius,
        row_spacing=row_spacing,
        col_spacing=col_spacing,
        display_radius_pixels=water_roi_radius,
        full_detected_radius_pixels=float(water.get("detectedWaterCircleRadius", water_roi_radius)),
    )
    water_roi["shortLabel"] = "Water"
    water_roi["circleNumber"] = 0
    water_roi["detectionMethod"] = str(water["method"])
    water_roi["waterSearch"] = water
    water_roi["targetAreaMm2"] = M1_V13_WATER_ROI_AREA_MM2
    water_roi["areaPolicy"] = "ROI placed inside detected faint outer water circle"
    water_roi = _m1v12_flag(water_roi)
    rois.append(water_roi)

    priority = {
        "Air": 0,
        "Polyethylene": 1,
        "Low-density insert": 1,
        "Acrylic / PMMA-like insert": 2,
        "Bone / high-density insert": 3,
        "Water / background": 4,
    }
    rois = sorted(rois, key=lambda r: priority.get(str(r["label"]), 99))

    overlay = window_pixels_to_image(
        raw,
        float(window_width),
        float(window_level),
        selected.get("photometric", "MONOCHROME2"),
    ).convert("RGB")
    draw = ImageDraw.Draw(overlay)

    draw.ellipse(
        [
            phantom_cx - phantom_radius,
            phantom_cy - phantom_radius,
            phantom_cx + phantom_radius,
            phantom_cy + phantom_radius,
        ],
        outline="yellow",
        width=2,
    )

    for insert in inserts:
        x = float(insert["x"])
        y = float(insert["y"])
        r = float(insert["radius"])
        draw.ellipse([x - r, y - r, x + r, y + r], outline="gray", width=1)

    # Draw detected OUTER water circle first.
    outer_r = float(water.get("detectedWaterCircleRadius", water_roi_radius))
    wx = float(water["cx"])
    wy = float(water["cy"])
    draw.ellipse(
        [wx - outer_r, wy - outer_r, wx + outer_r, wy + outer_r],
        outline="deepskyblue",
        width=1,
    )

    for roi in rois:
        cx = float(roi["cx"])
        cy = float(roi["cy"])
        rx = float(roi["radiusX"])
        ry = float(roi["radiusY"])
        label = str(roi["label"])

        if label.startswith("Water"):
            color = "cyan"
        elif "Air" in label:
            color = "red"
        elif "Bone" in label or "high-density" in label:
            color = "orange"
        elif "Polyethylene" in label or "Low-density" in label:
            color = "lime"
        else:
            color = "springgreen"

        draw.ellipse([cx - rx, cy - ry, cx + rx, cy + ry], outline=color, width=3)
        draw.text((cx + rx + 5, cy - ry), str(roi.get("shortLabel", label)), fill=color)

    module1_range = None
    if module1_group:
        module1_range = {
            "startSliceIndex": int(module1_group["startSliceIndex"]),
            "endSliceIndex": int(module1_group["endSliceIndex"]),
            "startSliceNumber": int(module1_group["startSliceNumber"]),
            "endSliceNumber": int(module1_group["endSliceNumber"]),
            "sliceCount": int(module1_group["sliceCount"]),
        }

    expected = {"Air", "Polyethylene", "Acrylic / PMMA-like insert", "Bone / high-density insert", "Water / background"}
    measured = {str(r["label"]) for r in rois}
    status = "MEASURED" if expected.issubset(measured) else "REVIEW"

    overlay_data = _image_to_data_url(overlay)

    return {
        "success": True,
        "analysisType": "Quick ACR Module 1 CT Number / Material Insert Analysis",
        "analysisVersion": MODULE1_ANALYSIS_VERSION,
        "classifierVersion": classification_result.get("classifierVersion", CLASSIFIER_VERSION),
        "sliceCount": len(slices),
        "selectedSliceIndex": int(slice_index),
        "selectedSliceNumber": int(slice_index) + 1,
        "selectedSliceLabel": selected.get("label", ""),
        "module1Range": module1_range,
        "selectedSliceClassifierRecord": slice_record,
        "sliceSelection": {
            "method": "cardinal edge-BB selected Module 1 slice",
            "candidateCount": int(len(slice_candidates)),
            "candidates": [{k: v for k, v in c.items() if k != "circles"} for c in slice_candidates[:12]],
        },
        "roiSizePolicy": {
            "materialInsertTargetAreaMm2": M1_V13_MATERIAL_ROI_AREA_MM2,
            "waterTargetAreaMm2": M1_V13_WATER_ROI_AREA_MM2,
            "note": "Water ROI is placed inside the detected faint outer water circle; it may be capped by that circle.",
        },
        "insertDetection": insert_detection,
        "waterSearch": water,
        "phantom": {
            "centerX": round(float(phantom_cx), 3),
            "centerY": round(float(phantom_cy), 3),
            "radiusPixels": round(float(phantom_radius), 3),
            "radiusMmApprox": round(float(phantom_radius * ((row_spacing + col_spacing) / 2.0)), 3),
        },
        "detection": {
            "method": "large material insert circles + detected faint outer water circle + inner ROI",
            "detectedInsertCount": int(len(inserts)),
            "expectedInsertCount": 4,
        },
        "rois": rois,
        "roiCount": int(len(rois)),
        "finalResult": {
            "status": status,
            "waterRoiMethod": "detect faint outer water circle first, then place ROI inside it",
            "note": "MEASURED means all four material inserts plus water/background were found. Temporary OK/CHECK flags use rough review bands only.",
        },
        "displayWindow": {
            "windowWidth": float(window_width),
            "windowLevel": float(window_level),
            "note": "WW/WL controls only the displayed overlay. ROI statistics use raw CT HU values.",
        },
        "overlayImage": overlay_data,
        "image": overlay_data,
        "warnings": warnings,
        "criteriaNote": (
            "Module 1 V21 detects the faint larger water circle first and then places the water ROI inside it. "
            "The overlay draws the larger detected water circle with a thin cyan outline and the measurement ROI with a thicker cyan outline. "
            "Polyethylene label is preserved."
        ),
    }

__all__ = ["create_module1_ct_number_analysis", "MODULE1_ANALYSIS_VERSION"]
